(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define arg1 (readInt))
    (define arg2 (readReal))
    (define arg3 (readReal))
    (println "((mandelbrot " arg1 ") " arg2 " " arg3 ") is " ((mandelbrot arg1) arg2 arg3))
    )

(define (div? a b)
    (cond 
        ((> (+ (* a a) (* b b)) 4) #t)
        (else #f)
        )
    )

(define (mandelbrot t)
    (define (helper x y) 
        (define (calR r s x)
            (+ (- (* r r) (* s s)) x)
            )
        (define (calS r s y)
            (+ (* (* 2 r) s) y)
            )
        (define (iter store1 store2 store3 src1 src2 thresh)
            (cond
                ((equal? #t (div? store1 store2)) store3)
                ((> store3 thresh) 0)
                (else (iter (calR store1 store2 src1) (calS store1 store2 src2) (+ store3 1) src1 src2 thresh))
                )
            )
        (iter 0.0 0.0 0 x y t)
        )
    helper
    )