(define (main)
   (setPort (open (getElement ScamArgs 1) 'read))
   (define arg1 (eval (readExpr) this))
   (define arg2 (readExpr))
   (define arg3 (readExpr))
   (define arg4 (readExpr))
   (define arg5 (readExpr))
   (println "(((((curry " arg1 ") " arg2 ") " arg3 ") " arg4 ") " arg5 ") is " 
      (((((curry arg1) arg2) arg3) arg4) arg5))
   )

(define (curry f) 
   (lambda (a)
      (lambda (b)
         (lambda (c)
            (lambda (d)
               (f a b c d)
               )
            )
         )
      )
   )
