(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (define arg1 (readExpr))
    (define arg2 (readExpr))
    (define arg3 (readExpr))
    (println "((crazyTriangle " arg1 " " arg2 ") " arg3 ")")
    ((crazyTriangle arg1 arg2) arg3)
    )

(define (crazyTriangle x y)
    (define (printTriangle z)
        (define (pascal x y) 
            (if (or (zero? y) (= x y))
                (println "1")
                (+ (pascal (sub1 x) y)
                (pascal (sub1 x) (sub1 y)))
                )
            )
        (define (spacePrint d) 
            (cond 
                ((= (+ d 1) z) (println " "))
                (else (println " ")
                    (spacePrint (+ d 1))
                    )
                )
            )
        )
    printTriangle
    )